language: node_js
node_js:
  - "9"
cache:
  yarn: true
  directories:
  - node_modules
before_deploy:
  - yarn test:output
  - yarn build-storybook
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: storybook-static
  keep-history: true
  on:
    branch: master
branches:
  only:
  - master
